kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 100Gi

---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: file-server
  labels:
    app: file-server
spec:
  selector:
    matchLabels:
      app: file-server
  template:
    metadata:
      labels:
        app: file-server
    spec:
      containers:
      - image:  edwardkan/fileserver:latest
        name: file-server
        resources:
          limits:
            memory: "1Gi"
          requests:
            memory: "512Mi"
        ports:
        - containerPort: 22
          protocol: TCP 
          name: sshserver
        - containerPort: 445
          protocol: TCP 
          name: smbd
        - containerPort: 139
          protocol: TCP 
          name: netbios
        - containerPort: 135
          protocol: TCP 
          name: scm
        - containerPort: 137
          protocol: UDP 
          name: netbeu
        - containerPort: 138
          protocol: UDP 
          name: updnetbios
        volumeMounts:
        - name: task-pv-storage
          mountPath: /mnt/coreStorage
      volumes:
      - name: task-pv-storage 
        persistentVolumeClaim:
          claimName: local-claim

---
apiVersion: v1
kind: Service
metadata:
  name: file-service
spec:
  type: NodePort
  ports:
  - port: 22
    nodePort: 30003
    protocol: TCP
    name: "ssh"
  - port: 445
    nodePort: 445
    protocol: TCP
    name: "smbd"
  - port: 139
    nodePort: 139
    protocol: TCP
    name: "netbios"
  - port: 135
    nodePort: 135
    protocol: TCP
    name: "scm"
  - port: 137
    nodePort: 137
    protocol: UDP
    name: "netbeu"
  - port: 138
    nodePort: 138
    protocol: UDP
    name: "upd-netbios"
  selector:
    app: file-server

